WebApp/Controllers/TasumiseViisidController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DAL.Contracts.App;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL.EF.App;
using Domain.App;

namespace WebApp.Controllers
{
    public class TasumiseViisidController : Controller
    {
        private readonly IAppUOW _uow;

        public TasumiseViisidController(IAppUOW uow)
        {
            _uow = uow;
        }

        // GET: TasumiseViisid
        public async Task<IActionResult> Index()
        {
            var vm = await _uow.TasumiseViisRepository.AllAsync();
            return View(vm);
        }

        // GET: TasumiseViisid/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tasumiseViis = await _uow.TasumiseViisRepository
                .FindAsync(id.Value);
            if (tasumiseViis == null)
            {
                return NotFound();
            }

            return View(tasumiseViis);
        }

        // GET: TasumiseViisid/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TasumiseViisid/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ViisNimetus,Id")] TasumiseViis tasumiseViis)
        {
            if (ModelState.IsValid)
            {
                tasumiseViis.Id = Guid.NewGuid();
                _uow.TasumiseViisRepository.Add(tasumiseViis);
                await _uow.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tasumiseViis);
        }

        // GET: TasumiseViisid/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tasumiseViis = await _uow.TasumiseViisRepository.FindAsync(id.Value);
            if (tasumiseViis == null)
            {
                return NotFound();
            }
            return View(tasumiseViis);
        }

        // POST: TasumiseViisid/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("ViisNimetus,Id")] TasumiseViis tasumiseViis)
        {
            if (id != tasumiseViis.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _uow.TasumiseViisRepository.Update(tasumiseViis);
                    await _uow.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TasumiseViisExists(tasumiseViis.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tasumiseViis);
        }

        // GET: TasumiseViisid/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tasumiseViis = await _uow.TasumiseViisRepository.FindAsync(id.Value);
            
            if (tasumiseViis == null)
            {
                return NotFound();
            }

            return View(tasumiseViis);
        }

        // POST: TasumiseViisid/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await _uow.TasumiseViisRepository.RemoveAsync(id);
            
            await _uow.SaveChangesAsync();
            
            return RedirectToAction(nameof(Index));
        }

        private bool TasumiseViisExists(Guid id)
        {
            return (_uow.TasumiseViisRepository?.FindAsync(id) == null);
        }
    }
}

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - RIK Üritus</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RIK Üritus</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="TasumiseViisid" asp-action="Index">Halda makseviise</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container" align="center">
        &copy; 2025 - ToSu
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>