WebApp/Controllers/IsikudController.cs
using DAL.Contracts.App;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Domain.App;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class IsikudController : Controller
    {
        private readonly IAppUOW _uow;

        public IsikudController(IAppUOW uow)
        {
            _uow = uow;
        }

        // GET: Isikud
        public async Task<IActionResult> Index()
        {
            var vm = await _uow.IsikRepository.AllAsync();
            return View(vm);
        }

        // GET: Isikud/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var isik = await _uow.IsikRepository
                .FindAsync(id.Value);
            if (isik == null)
            {
                return NotFound();
            }

            return View(isik);
        }

        // GET: Isikud/Create
        public async Task<IActionResult> Create(Guid yritusId)
        {
            var tasumiseViisid = await _uow.TasumiseViisRepository.AllAsync();
            
            var vm = new IsikCreateViewModel()
            {
                Isik = new Isik(),
                YritusId = yritusId,
                TasumiseViisid = tasumiseViisid.Select(t => new SelectListItem
                {
                    Value = t.Id.ToString(),
                    Text = t.ViisNimetus
                })
            };
            
            ViewData["OsavotumaksId"] = new SelectList(await _uow.OsavotumaksRepository.AllAsync(), "Id", "id");
            return View(vm);
        }

        // POST: Isikud/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IsikCreateViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                foreach (var entry in ModelState)
                {
                    foreach (var error in entry.Value.Errors)
                    {
                        Console.WriteLine($"{entry.Key}: {error.ErrorMessage}");
                    }
                }
                vm.TasumiseViisid = (await _uow.TasumiseViisRepository.AllAsync())
                    .Select(t => new SelectListItem
                    {
                        Value = t.Id.ToString(),
                        Text = t.ViisNimetus
                    });
                return View(vm);
            }

            var osavotumaksuStaatusId =
                (await _uow.OsavotumaksuStaatusRepository.AllAsync())
                .Where(o => !o.Staatus)
                .Select(o => o.Id)
                .FirstOrDefault();

            var osavotumaks = new Osavotumaks
            {
                Id = Guid.NewGuid(),
                TasumiseViisId = vm.SelectTasumiseViisId,
                OsavotumaksuStaatusId = osavotumaksuStaatusId
            };
            
            vm.Isik.Id = Guid.NewGuid();
            vm.Isik.Osavotumaks = osavotumaks;
            _uow.IsikRepository.Add(vm.Isik);

            var isikYritusel = new IsikYritusel
            {
                Id = Guid.NewGuid(),
                YritusId = vm.YritusId,
                IsikId = vm.Isik.Id,
            };
            _uow.IsikYrituselRepository.Add(isikYritusel);
            await _uow.SaveChangesAsync();
            
            return RedirectToAction("Index", "Home");
        }

        // GET: Isikud/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var isik = await _uow.IsikRepository.FindAsync(id.Value);
            if (isik == null)
            {
                return NotFound();
            }
            ViewData["OsavotumaksId"] = new SelectList(await _uow.OsavotumaksRepository.AllAsync(), "Id", "Id", isik.OsavotumaksId);
            return View(isik);
        }

        // POST: Isikud/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("OsavotumaksId, Eesnimi,Perenimi,Isikukood,Lisainfo,Id")] Isik isik)
        {
            if (id != isik.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _uow.IsikRepository.Update(isik);
                    await _uow.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!IsikExists(isik.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["OsavotumaksId"] = new SelectList(await _uow.OsavotumaksRepository.AllAsync(), "Id", "Id", isik.OsavotumaksId);
            return RedirectToAction("Index", "Home");
        }

        // GET: Isikud/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var isik = await _uow.IsikRepository.FindAsync(id.Value);
            
            if (isik == null)
            {
                return NotFound();
            }

            return View(isik);
        }

        // POST: Isikud/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await _uow.IsikRepository.RemoveAsync(id);
            
            await _uow.SaveChangesAsync();
            
            return RedirectToAction("Index", "Home");
        }

        private bool IsikExists(Guid id)
        {
            return (_uow.IsikRepository?.FindAsync(id) == null);
        }
    }
}

WebApp/Controllers/YritusedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DAL.Contracts.App;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL.EF.App;
using Domain.App;

namespace WebApp.Controllers
{
    public class YritusedController : Controller
    {
        private readonly IAppUOW _uow;

        public YritusedController(IAppUOW uow)
        {
            _uow = uow;
        }
        
        // GET: Yritused
        public async Task<IActionResult> Index()
        {
            var vm = await _uow.YritusRepository.AllAsync();
            return View(vm);
        }

        // GET: Yritused/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var yritus = await _uow.YritusRepository
                .FindAsync(id.Value);
            if (yritus == null)
            {
                return NotFound();
            }
            return View(yritus);
        }

        // GET: Yritused/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Yritused/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nimi,Algus,Lopp,Asukoht,Id")] Yritus yritus)
        {
            if (ModelState.IsValid)
            {
                yritus.Id = Guid.NewGuid();
                _uow.YritusRepository.Add(yritus);
                await _uow.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }
            return View(yritus);
        }

        // GET: Yritused/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var yritus = await _uow.YritusRepository.FindAsync(id.Value);
            if (yritus == null)
            {
                return NotFound();
            }
            return View(yritus);
        }

        // POST: Yritused/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Nimi,Algus,Lopp,Asukoht,Id")] Yritus yritus)
        {
            if (id != yritus.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _uow.YritusRepository.Update(yritus);
                    await _uow.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!YritusExists(yritus.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "Home");
            }
            return View(yritus);
        }

        // GET: Yritused/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var yritus = await _uow.YritusRepository.FindAsync(id.Value);
            
            if (yritus == null)
            {
                return NotFound();
            }

            return View(yritus);
        }

        // POST: Yritused/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await _uow.YritusRepository.RemoveAsync(id);
            
            await _uow.SaveChangesAsync();
            
            return RedirectToAction("Index", "Home");
        }

        private bool YritusExists(Guid id)
        {
            return (_uow.YritusRepository?.FindAsync(id) == null);
        }
    }
}

WebApp/Views/Yritused/Create.cshtml
@model Domain.App.Yritus

@{
    ViewData["Title"] = "Lisa uus üritus";
}

<h1>Lisa uus üritus</h1>

<h4>Üritus</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nimi" class="control-label"></label>
                <input asp-for="Nimi" class="form-control" />
                <span asp-validation-for="Nimi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Algus" class="control-label"></label>
                <input asp-for="Algus" class="form-control" />
                <span asp-validation-for="Algus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lopp" class="control-label"></label>
                <input asp-for="Lopp" class="form-control" />
                <span asp-validation-for="Lopp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Asukoht" class="control-label"></label>
                <input asp-for="Asukoht" class="form-control" />
                <span asp-validation-for="Asukoht" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Lisa" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Home" asp-action="Index">Tagasi</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/Views/Yritused/Delete.cshtml
@model Domain.App.Yritus

@{
    ViewData["Title"] = "Kustuta üritus";
}

<h1>Kustuta üritus</h1>

<h3>Oled kindel, et soovid ürituse kustutada?</h3>
<div>
    <h4>Yritus</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nimi)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nimi)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Algus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Algus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lopp)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lopp)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Asukoht)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Asukoht)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Kustuta" class="btn btn-danger" /> |
        <a asp-controller="Home" asp-action="Index">Tagasi</a>
    </form>
</div>

WebApp/Views/Yritused/Details.cshtml
@model Domain.App.Yritus

@{
    ViewData["Title"] = "Ürituse info";
}

<h1>Details</h1>

<div>
    <h4>Yritus</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nimi)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nimi)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Algus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Algus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lopp)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lopp)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Asukoht)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Asukoht)
        </dd>
        <dd class="col-sm-10">
            @if (Model.IsikudYritusel != null)
            {
                <table>
                    <thead>
                    <tr>
                        <th>Eesnimi / Nimetus</th>
                        <th>Perenimi / Liik</th>
                        <th>Isikukood / Registrikood</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach (var osaleja in Model.IsikudYritusel)
                    {
                        <tr>
                            <td><a asp-controller="Isikud" asp-action="Details" asp-route-id="@osaleja.Isik!.Id">@osaleja.Isik!.Eesnimi</a></td>
                            <td>@osaleja.Isik!.Perenimi</td>
                            <td>@osaleja.Isik.Isikukood</td>
                        </tr>
                    }
                    </tbody>
                </table>
            }
            @if (Model.IsikudYritusel == null)
            {
                <div><b>Üritusel puuduvad osalejad</b></div>
            }
        </dd>
    </dl>
</div>
<div>
    <a asp-controller="Home" asp-action="Index">Tagasi</a>
</div>

WebApp/Views/Yritused/Edit.cshtml
@model Domain.App.Yritus

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Yritus</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nimi" class="control-label"></label>
                <input asp-for="Nimi" class="form-control" />
                <span asp-validation-for="Nimi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Algus" class="control-label"></label>
                <input asp-for="Algus" class="form-control" />
                <span asp-validation-for="Algus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lopp" class="control-label"></label>
                <input asp-for="Lopp" class="form-control" />
                <span asp-validation-for="Lopp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Asukoht" class="control-label"></label>
                <input asp-for="Asukoht" class="form-control" />
                <span asp-validation-for="Asukoht" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Home" asp-action="Index">Tagasi</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}